# Generated by Django 5.2.4 on 2025-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
