# Generated by Django 5.2.4 on 2025-07-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midia',
            old_name='file',
            new_name='arquivo',
        ),
        migrations.RenameField(
            model_name='midia',
            old_name='description',
            new_name='descricao',
        ),
    ]
