# Generated by Django 5.2.4 on 2025-07-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_file_midia_arquivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midia',
            old_name='arquivo',
            new_name='file',
        ),
    ]
