# Generated by Django 5.2.4 on 2025-07-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_passage_id_user_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
        migrations.AddField(
            model_name='user',
            name='CPF',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
    ]
