# Generated by Django 5.2.6 on 2025-09-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_item_tempo_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nome_rua',
            field=models.CharField(blank=True, help_text='Nome da rua do usuario.', max_length=200, null=True),
        ),
    ]
