# Generated by Django 5.2.4 on 2025-07-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_cpf_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CPF',
            field=models.CharField(default=None, help_text='CPF do usuário', max_length=11, null=True),
        ),
    ]
