# Generated by Django 5.2.4 on 2025-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_arquivo_midia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_aluguel',
            name='dias',
            field=models.IntegerField(default=0),
        ),
    ]
