# Generated by Django 5.2.4 on 2025-07-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_aluguel_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='total',
        ),
        migrations.RemoveField(
            model_name='item_aluguel',
            name='dias',
        ),
        migrations.AddField(
            model_name='item_aluguel',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_aluguel',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
