# Generated by Django 5.2.4 on 2025-07-11 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='avaliacao_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
                ('estrelas', models.DecimalField(decimal_places=1, max_digits=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='avaliacao_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
                ('estrelas', models.DecimalField(decimal_places=1, max_digits=1)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliado', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
