# Generated by Django 5.2.4 on 2025-07-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_aluguel_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuário')], default='usuario', max_length=10),
        ),
    ]
