# Generated by Django 5.2.4 on 2025-07-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aluguel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, max_length=10)),
                ('aluguel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.aluguel')),
            ],
        ),
    ]
