# Generated by Django 5.2.4 on 2025-07-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('padrao', 'Padrão')], default='usuario', max_length=10),
        ),
    ]
