# Generated by Django 5.2.4 on 2025-07-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_aluguel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_aluguel',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
