# Generated by Django 5.2.4 on 2025-07-11 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aluguel_item_aluguel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('chave_midia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Midia_itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item')),
                ('midia', models.ManyToManyField(blank=True, related_name='Midia', to='core.midia')),
            ],
        ),
    ]
