# Generated by Django 5.2.4 on 2025-08-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_aluguel_options_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='midia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.midia'),
        ),
    ]
