# Generated by Django 5.2.4 on 2025-08-05 18:08

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_midia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='midia',
        ),
        migrations.AddField(
            model_name='user',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user.image_file_path),
        ),
    ]
