# Generated by Django 5.2.4 on 2025-08-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_midia_user_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='CPF',
            new_name='cpf',
        ),
    ]
