# Generated by Django 5.2.5 on 2025-09-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_cpf_user_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
