# Generated by Django 5.2.6 on 2025-09-05 14:42

import core.models.item
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.item.image_file_path),
        ),
        migrations.AddField(
            model_name='item',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Localização do usuário', max_length=100, null=True),
        ),
    ]
