# Generated by Django 5.2.6 on 2025-09-05 14:48

import core.models.user
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_imagem_item_localizacao_user_localizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='item',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='item',
            name='nome_rua',
            field=models.CharField(blank=True, help_text='Nome da rua do usuario.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='numero',
            field=models.CharField(blank=True, help_text='Numero da casa do usuario.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_rua',
            field=models.CharField(blank=True, help_text='Nome da rua do usuario.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='numero',
            field=models.CharField(blank=True, help_text='Numero da casa do usuario.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Nome da rua dia usuario.', null=True, upload_to=core.models.user.image_file_path),
        ),
        migrations.AddField(
            model_name='item',
            name='condicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.condicao'),
        ),
    ]
