# Generated by Django 5.2.6 on 2025-09-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_condicao_remove_item_imagem_remove_item_localizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
