# Generated by Django 5.2.6 on 2025-09-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_item_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quant_estoque',
            field=models.IntegerField(default=0),
        ),
    ]
