# Generated by Django 5.2.6 on 2025-09-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_item_quant_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia_item',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='midia_item', to='core.item'),
        ),
    ]
