# Generated by Django 5.2.6 on 2025-09-15 11:58

import a_users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Email', max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, help_text='Username', max_length=255, null=True, verbose_name='name')),
                ('cpf', models.CharField(default=None, help_text='CPF do usuário', max_length=11, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica que este usuário está ativo.', verbose_name='Usuário está ativo')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('padrao', 'Padrão')], default='padrao', max_length=10)),
                ('numero', models.CharField(blank=True, help_text='Numero da casa do usuario.', max_length=10, null=True)),
                ('nome_rua', models.CharField(blank=True, help_text='Nome da rua do usuario.', max_length=10, null=True)),
                ('imagem', models.ImageField(blank=True, help_text='Nome da rua dia usuario.', null=True, upload_to=a_users.models.image_file_path)),
                ('is_staff', models.BooleanField(default=False, help_text='Indica que este usuário pode acessar o Admin.', verbose_name='Usuário é da equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', a_users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
