# Generated by Django 5.2.5 on 2025-08-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='gruop',
            new_name='group',
        ),
    ]
