# Generated by Django 5.2.5 on 2025-08-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0002_rename_gruop_groupmessage_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='autor',
            new_name='author',
        ),
    ]
