# Generated by Django 5.2.5 on 2025-09-02 18:35

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0005_chatgroup_isprivate_chatgroup_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='isPrivate',
            new_name='is_private',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
